= Long bean sandwich

== Ingredients

* 1 lb (454g) Chinese long beans (available at Asian markets here in the U.S.)
* 1 long bread loaf, about as long as the beans (get the softest bread you can)
* 1 red onion
* 2 fresh red chilies
* 8 oz (227g) cheese slices (I used munster but any cheese that melts will work)
* starch
* 200g soy sauce
* 50g honey (or any other sweetener)
* granulated sugar
* ginger (I used dried powder for this)
* garlic (I also used dried powder for this)
* vinegar
* oil
* salt

== Recipe

1. First make pink pickled onions. Slice the red onion into thin wedges from tip to root. Bring enough vinegar to cover them to a boil along with a pinch of salt and a handful of sugar. Pour the hot vinegar over the onions and let everything cool down. This produces more pickles than you'll need for the sandwich, but you can keep them in the fridge for a couple weeks and use them on everything.

2. Second make the sauce. Disperse about a tablespoon of starch in just enough water to make a smooth slurry. Pour in the soy sauce, a big glug of honey or whatever sweetener you're using, a dash of garlic powder, a dash of ginger powder and a splash of the juice from the pickled onions. Bring to a boil and reduce until it's as thick as you want it, stirring constantly to make sure the sugar doesn't stick to the bottom and burn. Cool the sauce until you can taste it and then adjust, adding more of the sugar or the pickle juice or whatever it needs. It should taste way too salty and strong on its own.

3. Get your grill heating to a moderate temperature. Cut the bread in half, lengthwise. Trim the ends of the beans and cut off any extra length they may have — you want them to fit on the sandwich, but remember they'll shrink a little during cooking. Toss the beans in a thin coating of oil and a little salt (remember the sauce is salty). Slice the chilies thinly. If necessary, cut the cheese slices so that you have smaller pieces that won't hang over the sides of the sandwich too far. Take everything outside to the grill.

4. Lay the beans onto the grill and close the lid. Let them cook a few minutes until they've got some nice browning and they're starting to get pretty soft — if they're al dente, they'll be too stringy and hard to eat in a sandwich.

5. Lay the bread on the grill cut-side down and toast until you have a little color. Flip the bread around. Cover one of the top sides with cheese slices, then lay on half of the beans (I use two sets of tongs to lift them). Top the beans with sauce, pickled onions, chili slices and another layer of cheese slices. Lay on the rest of the beans, then top with sauce, pickled onions, chili slices and the final layer of cheese slices. Top with the other pieces of bread.

[NOTE]
====
If you want a super crispy texture, just close the lid and let the sandwich heat through. If you want a softer texture, wrap the sandwich in foil and let it steam through with its own moisture.
====

== Source

https://www.youtube.com/watch?v=Rwdpt_9Dkz8[Adam Raguseau, Youtube]
